version: "3"

services:
  bitcoind:
    image: bitcoind
    container_name: bitcoind
    volumes:
      - bitcoin-data:/data
      - ./bitcoind/bitcoin.conf:/root/.bitcoin/bitcoin.conf
    networks:
      - bitcoin
    stdin_open: true
    tty: true
    ports:
      - "8332:8332"
      - "8333:8333"

volumes:
  bitcoin-data:

networks:
  bitcoin:
